### ISSUE TITLE
mkinitcpio hook calculates checksums before initramfs is built

### ISSUE THREAD

**Issue by giddie** [grazzolini/chkboot#7]
Since the initramfs is built and copied to /boot after all the hooks are run, chkboot thinks that the initramfs has been modified immediately following a `mkinitcpio -p linux`.

**Comment by giddie** [comment]
Slightly off-topic, but I'd be really interested in your opinion: I've been wondering about whether a simpler signing mechanism would be possible. I'm thinking that it should be possible to write a unit to run after /boot is unmounted, which checksums the whole /boot partition and stores the hash. On bootup, a unit defined before boot.mount checks for differences. This would be very strict: even mounting the /boot partition would result in a checksum failure, I expect. However, it might be quite an elegant solution. Any thoughts?

**Comment by grazzolini** [comment]
@giddie 
It would rely heavily on systemd, but I don't see that strictly as a bad thing. I assumed this project because I wrote chkcryptoboot and I planned on merging both that and chkboot together. That didn't happened yet, but it is still on my plans. The original author wasn't interested on keeping the project anymore, so I ended up having to fork it and took over the AUR package.

I planned to also add an inotify layer to chkboot (in the form of a daemon or something else) that would detect the changes to /boot as they happened and would warn the user, or ask for a rebuild. Recently I accepted and modified a pull request that adds graphical notifications.

Your suggestion, possibly, could take this in another direction. Can you improve the description of how this flux would work? Answering your first question, yes, running chkboot from mkinitcpio itself isn't the best way to do this. It was there when I assumed the project and I never got around to fix it. Possibly with the recently introduced pacman hooks, I could do something in that regard.

**Comment by giddie** [comment]
Well, right now I'm afraid I can't offer any more detail than what I've already suggested. I'm working on the units in spare moments, and I'll let you know if I get anywhere.

**Comment by giddie** [comment]
OK, I've had a stab at this, and it seems to be working OK in tests so far. It remains to be seen how well it works in practice. Care to take a look?

https://aur.archlinux.org/packages/checksum-block-device/
https://github.com/giddie/checksum-block-device

**Comment by giddie** [comment]
Oh, to use this, you'll need to:

```
systemctl enable checksum-block-device@sda1
systemctl enable checksum-block-device-on-sleep@sda1
```

Where `sda1` should be replaced with the boot partition.

**Comment by grazzolini** [comment]
I'll take a look at them. Seems nice to me.
